server:
  port: 8045
  servlet:
    context-path:
spring:
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
      url: jdbc:mysql://localhost:3306/gujinlong?useUnicode=true&characterEncoding=UTF8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.meihao.uploadexcel

